mindmaps.Event = {
    DOCUMENT_OPENED: "DocumentOpenedEvent",
    DOCUMENT_SAVED: "DocumentSavedEvent",
    DOCUMENT_CLOSED: "DocumentClosedEvent",
    NODE_SELECTED: "NodeSelectedEvent",
    NODE_DESELECTED: "NodeDeselectedEvent",
    NODE_MOVED: "NodeMovedEvent",
    NODE_TEXT_CAPTION_CHANGED: "NodeTextCaptionChangedEvent",
    NODE_BORDER_CHANGED: "NodeBorderChangedEvent",
    NODE_FONT_CHANGED: "NodeFontChangedEvent",
    TWO_NODES_CONNECTED: "TwoNodesConnected",
    TWO_NODES_DISCONNECTED: "TwoNodesDisconnected",
    CONNECTION_COLOR_CHANGED: "ConnectionColorChanged",
    NODE_LINE_WIDTH_CHANGED: "NodeLineWidthChangedEvent",
    NODE_FONT_COLOR_PREVIEW: "NodeFontColorPreviewEvent",
    NODE_BRANCH_COLOR_CHANGED: "NodeBranchColorChangedEvent",
    CONNECT_BUTTON_CLICKED: "ConnectButtonClickedEvent",
    CONNECTED_TWO_NODES: "ConnectedTwoNodesEvent",
    CONNECTION_COLOR_CHANGED: "ConnectionColorChanged",
    NODE_BRANCH_COLOR_PREVIEW: "NodeBranchColorPreviewEvent",
    NODE_CREATED: "NodeCreatedEvent",
    NODE_DELETED: "NodeDeletedEvent",
    NODE_OPENED: "NodeOpenedEvent",
    NODE_CLOSED: "NodeClosedEvent",
    ZOOM_CHANGED: "ZoomChangedEvent",
    NOTIFICATION_INFO: "NotificationInfoEvent",
    NOTIFICATION_WARN: "NotificationWarnEvent"
}, mindmaps.EventBus = EventEmitter, mindmaps.EventBus.prototype.setMaxListeners(15);