/* Copyright CloudTop 2012. All Rights Reserved. */
var filepicker=(function(){var apiKey;var setAPIKey=function(key){apiKey=key;};var BASE_URL="https://www.filepicker.io";var MIMETYPES={ALL:'*/*',IMAGES:'image/*',JPG:'image/jpeg',GIF:'image/gif',PNG:'image/png',PDF:'application/pdf',AUDIO:'audio/*',MP3:'audio/mpeg',TEXT:'text/*',HTML:'text/html',XML:'text/xml',VCARD:'text/vcard',VIDEO:'video/*',MPEG:'video/mpeg',MP4:'video/mp4'};var NEW_WINDOW=true;var THIRD_PARTY_COOKIES;var FilepickerException=function(text){this.text=text;this.toString=function(){return"FilepickerException: "+this.text;};};var isArray=function(o){return Object.prototype.toString.call(o)==='[object Array]';};var DIALOG_TYPES={OPEN:'/open/',SAVEAS:'/saveas/'};var pickerWindowProperties="left=100,top=100,height=600,width=800,menubar=no,toolbar=no,location=no,personalbar=no,status=no,resizable=yes,scrollbars=yes,dependent=yes,dialog=yes";var WINDOW_NAME="filepicker_dialog";var WINDOW_CONTAINER_NAME="filepicker_dialog_container";var SHADE_NAME="filepicker_shade";var IFRAME_NAME="filepicker_iframe";var COMM_IFRAME_NAME="filepicker_comm_iframe";var endpoints={};endpoints.tempStorage=BASE_URL+"/api/v0/util/tempStorage";endpoints.commUrl=BASE_URL+"/comm_iframe/";endpoints.open=BASE_URL+DIALOG_TYPES.OPEN;endpoints.saveas=BASE_URL+DIALOG_TYPES.SAVEAS;var constructOpenURL=function(mimetypes,id,options){return endpoints.open+"?m="+mimetypes.join(",")+"&key="+apiKey+"&id="+id+"&modal="+(options['modal']||!NEW_WINDOW)+
(options['services']?"&s="+options['services'].join(","):"")+
(options['multiple']?"&multi="+options['multiple']:"")+
(options['location']!==undefined?"&loc="+options['location']:"")+
(options['persist']?"&p="+options['persist']:"");};var constructSaveAsURL=function(fileurl,mimetype,id,options){return endpoints.saveas+"?url="+fileurl+"&m="+mimetype+"&key="+apiKey+"&id="+id+"&modal="+(options.modal||!NEW_WINDOW)+
(options['services']?"&s="+options['services']:"")+
(options['location']!==undefined?"&loc="+options['location']:"");};var openCommIframe=function(){if(window.frames[COMM_IFRAME_NAME]===undefined){ openCommunicationsChannel(); var commIFrame;commIFrame=document.createElement("iframe");commIFrame.name=COMM_IFRAME_NAME;commIFrame.src=endpoints.commUrl;commIFrame.style.display='none';document.body.appendChild(commIFrame);}};var openCommunicationsChannel=function(){if(openCommunicationsChannel.set){return;}else{openCommunicationsChannel.set=true;}
var communicationsHandler=function(event){if(event.origin!=BASE_URL){return;}
var data=JSON.parse(event.data);handlers.run(data);}; if(window.addEventListener){window.addEventListener("message",communicationsHandler,false);}else if(window.attachEvent){window.attachEvent("onmessage",communicationsHandler);}else{throw new FilepickerException("Unsupported browser");}};var getReceiveUrlMessage=function(callback,multiple){var handler=function(data){if(data.type!=="filepickerUrl"){return;} 
if(isArray(data.payload)){callback(data.payload);}else if(multiple){callback([data.payload]);}else{callback(data.payload.url,data.payload.data);}
closeModal();};return handler;};var getReceiveCookiesMessage=function(callback){var handler=function(data){if(data.type!=="ThirdPartyCookies"){return;}
THIRD_PARTY_COOKIES=!!data.payload;if(callback){callback(!!data.payload);}};return handler;};var handlers={};handlers._storage={'cookies':getReceiveCookiesMessage()};handlers.attachHandler=function(id,handler){handlers._storage[id]=handler;return handler;};handlers.detachHandler=function(id){return delete(handlers._storage[id]);};handlers.run=function(data){var callerId=data.id;if(handlers._storage.hasOwnProperty(callerId)){handlers._storage[callerId](data);handlers.detachHandler(callerId);return true;}
return false;};var generateModal=function(modalUrl){var shade=createModalShade();var container=createModalContainer();var close=createModalClose();var modal=document.createElement("iframe");modal.name=WINDOW_NAME;modal.id=WINDOW_NAME;var size=getWindowSize();var height=Math.min(size[1]-40,500);modal.style.width='100%';modal.style.height=height-32+'px';modal.style.border="none";modal.style.position="relative";modal.src=modalUrl;document.body.appendChild(shade);container.appendChild(close);container.appendChild(modal);document.body.appendChild(container);return modal;};var createModalShade=function(){var shade=document.createElement("div");shade.id=SHADE_NAME;shade.style.position='fixed';shade.style.top=0;shade.style.bottom=0;shade.style.right=0;shade.style.left=0;shade.style.backgroundColor='#000000';shade.style.opacity='0.5';shade.style.zIndex=10000;shade.onclick=filepicker.closeModal;return shade;};var createModalContainer=function(){var modalcontainer=document.createElement("div");modalcontainer.id=WINDOW_CONTAINER_NAME;modalcontainer.style.position='fixed';modalcontainer.style.padding="10px";modalcontainer.style.background="white";modalcontainer.style.top='10px';modalcontainer.style.bottom='auto';modalcontainer.style.right='auto';modalcontainer.style.left='50%';var size=getWindowSize();var height=Math.min(size[1]-40,500);var width=Math.min(size[0]-40,800);var leftmargin=-((width+40)/2-10);modalcontainer.style.height=height+'px';modalcontainer.style.width=width+'px';modalcontainer.style.overflow='auto';modalcontainer.style.webkitOverflowScrolling='touch';modalcontainer.style.border='1px solid #999';modalcontainer.style.webkitBorderRadius='6px';modalcontainer.style.borderRadius='6px';modalcontainer.style.margin='0 0 0'+leftmargin+'px';modalcontainer.style.webkitBoxShadow='0 3px 7px rgba(0, 0, 0, 0.3)';modalcontainer.style.boxShadow='0 3px 7px rgba(0, 0, 0, 0.3)';modalcontainer.style.zIndex=10001;return modalcontainer;};var createModalClose=function(){var close=document.createElement("a");close.appendChild(document.createTextNode('\u00D7'));close.onclick=filepicker.closeModal;close.style['float']="right";close.style.cursor="default";close.style.padding='0 5px 0 0px';close.style.fontSize='1.5em';close.style.color='#000000';close.style.textDecoration='none';return close;};var closeModal=function(){var shade=document.getElementById(SHADE_NAME);if(shade){document.body.removeChild(shade);}
var container=document.getElementById(WINDOW_CONTAINER_NAME);if(container){document.body.removeChild(container);}};var getID=function(){d=new Date();return d.getTime().toString();};var getFile=function(mimetype,options,callback){return openFilepickerWindow(DIALOG_TYPES.OPEN,{'mimetype':mimetype,'options':options,'callback':callback});};var saveFileAs=function(file_url,mimetype,options,callback){return openFilepickerWindow(DIALOG_TYPES.SAVEAS,{'file_url':file_url,'mimetype':mimetype,'options':options,'callback':callback});};var openFilepickerWindow=function(dialogType,arguments){ var picker;var handler;var file_url;if(!apiKey){throw new FilepickerException("API Key not found");}
if(dialogType!=DIALOG_TYPES.OPEN&&dialogType!=DIALOG_TYPES.SAVEAS){return null;}
if(dialogType==DIALOG_TYPES.SAVEAS){ file_url=arguments['file_url'];}
var mimetype=arguments['mimetype'];var options=arguments['options'];var callback=arguments['callback']; mimetype=mimetype||MIMETYPES.ALL;if(!isArray(mimetype)){mimetype=[mimetype];}
if(options['services']&&!isArray(options['services'])){options['services']=[options['services']];}
if(typeof options==="function"){callback=options;options={};}
callback=callback||function(){}; if(options['debug']){ dummy_url="https://www.filepicker.io/api/file/MApNBWILRHCWjggyjcWM";data={'filename':'test.png','type':'image/png','size':58979};window.setTimeout(function(){if(options['multiple']){callback([{'url':dummy_url,'data':data},{'url':dummy_url,'data':data}]);}else{callback(dummy_url,data);}},100);return window;}
var modal=options['modal']||!NEW_WINDOW;var smallScreen=(getWindowSize()[0]<768);modal=modal&&!smallScreen; if(THIRD_PARTY_COOKIES!==undefined){modal=modal&&THIRD_PARTY_COOKIES;}
if(modal){if(THIRD_PARTY_COOKIES===undefined){var cookie_callback=function(){if(dialogType==DIALOG_TYPES.OPEN){getFile(mimetype,options,callback);}else if(dialogType==DIALOG_TYPES.SAVEAS){saveFileAs(file_url,mimetype,options,callback);}};handler=getReceiveCookiesMessage(cookie_callback);handlers.attachHandler('cookies',handler);openCommIframe();return null;}}else{openCommIframe();}
var id=getID();var url;if(dialogType==DIALOG_TYPES.OPEN){url=constructOpenURL(mimetype,id,options);}else if(dialogType==DIALOG_TYPES.SAVEAS){url=constructSaveAsURL(file_url,mimetype,id,options);}
if(modal){picker=generateModal(url);}else{picker=window.open(url,WINDOW_NAME,pickerWindowProperties);}
handlers.attachHandler(id,getReceiveUrlMessage(callback,!!options['multiple']));return picker;};var Base64={ _keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=", encode:function(input){var output="";var chr1,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;input=Base64._utf8_encode(input);while(i<input.length){chr1=input.charCodeAt(i);chr2=input.charCodeAt(i+1);chr3=input.charCodeAt(i+2);i+=3;enc1=chr1>>2;enc2=((chr1&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else if(isNaN(chr3)){enc4=64;}
output=output+
this._keyStr.charAt(enc1)+this._keyStr.charAt(enc2)+
this._keyStr.charAt(enc3)+this._keyStr.charAt(enc4);}
return output;}, decode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;input=input.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<input.length){enc1=this._keyStr.indexOf(input.charAt(i));enc2=this._keyStr.indexOf(input.charAt(i+1));enc3=this._keyStr.indexOf(input.charAt(i+2));enc4=this._keyStr.indexOf(input.charAt(i+3));i+=4;chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;output=output+String.fromCharCode(chr1);if(enc3!=64){output=output+String.fromCharCode(chr2);}
if(enc4!=64){output=output+String.fromCharCode(chr3);}}
output=Base64._utf8_decode(output);return output;}, _utf8_encode:function(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128){utftext+=String.fromCharCode(c);}
else if((c>127)&&(c<2048)){utftext+=String.fromCharCode((c>>6)|192);utftext+=String.fromCharCode((c&63)|128);}
else{utftext+=String.fromCharCode((c>>12)|224);utftext+=String.fromCharCode(((c>>6)&63)|128);utftext+=String.fromCharCode((c&63)|128);}}
return utftext;}, _utf8_decode:function(utftext){var string="";var i=0;var c=c1=c2=0;while(i<utftext.length){c=utftext.charCodeAt(i);if(c<128){string+=String.fromCharCode(c);i++;}
else if((c>191)&&(c<224)){c2=utftext.charCodeAt(i+1);string+=String.fromCharCode(((c&31)<<6)|(c2&63));i+=2;}
else{c2=utftext.charCodeAt(i+1);c3=utftext.charCodeAt(i+2);string+=String.fromCharCode(((c&15)<<12)|((c2&63)<<6)|(c3&63));i+=3;}}
return string;}};var getWindowSize=function(){if(document.body&&document.body.offsetWidth){winW=document.body.offsetWidth;winH=document.body.offsetHeight;}
if(document.compatMode=='CSS1Compat'&&document.documentElement&&document.documentElement.offsetWidth){winW=document.documentElement.offsetWidth;winH=document.documentElement.offsetHeight;}
if(window.innerWidth&&window.innerHeight){winW=window.innerWidth;winH=window.innerHeight;}
return[winW,winH];};var getUrlFromData=function(fileContents,callback){if(!fileContents){throw'Error: no contents given';}
var returnData;var base64contents=Base64.encode(fileContents);var request=utilities.ajax({method:'POST',url:endpoints.tempStorage,data:{fileContents:base64contents},json:true,success:function(returnJson){returnData=returnJson;if(returnData){callback(returnData.url);}else{callback(null);}},error:function(msg){callback(null);}});};var getContents=function(file_url,base64encode,callback){if(typeof base64encode==="function"){callback=base64encode;base64encode=false;} 
base64encode=!!base64encode;utilities.ajax({method:'GET',url:file_url,data:{'base64encode':base64encode},success:function(responseText){callback(responseText);}});};var revokeFile=function(file_url,callback){if(!apiKey){throw new FilepickerException("API Key not found");}
file_url+='/revoke';var request=utilities.ajax({method:'POST',url:file_url,success:function(responseText){callback(true,"success");},error:function(responseText){callback(false,responseText);},data:{"key":apiKey}});}; var utilities={};utilities.typeOf=function(value){if(value===null){return'null';}else if(Object.prototype.toString.apply(value)==='[object Array]'){return'array';}
return typeof value;};utilities.JSON=(function(){if(typeof JSON=='undefined')this.JSON={};var special={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};var escape=function(chr){return special[chr]||'\\u'+('0000'+chr.charCodeAt(0).toString(16)).slice(-4);};var validate=function(string){string=string.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,'');return(/^[\],:{}\s]*$/).test(string);};var encode=JSON.stringify?function(obj){return JSON.stringify(obj);}:function(obj){if(obj&&obj.toJSON)obj=obj.toJSON();switch(utilities.typeOf(obj)){case'string':return'"'+obj.replace(/[\x00-\x1f\\"]/g,escape)+'"';case'array':return'['+obj.map(encode).clean()+']';case'object':case'hash':var string=[];Object.each(obj,function(value,key){var json=encode(value);if(json)string.push(encode(key)+':'+json);});return'{'+string+'}';case'number':case'boolean':return''+obj;case'null':return'null';default:return'null';}
return null;};var decode=function(string,secure){if(!string||utilities.typeOf(string)!='string')return null;if(JSON.parse){return JSON.parse(string);}else{if(secure){if(!validate(string))throw new Error('JSON could not decode the input; security is enabled and the value is not secure.');}
return eval('('+string+')');}};return{validate:validate,encode:encode,decode:decode};})();utilities.ajax=(function(){var toQueryString=function(object,base){var queryString=[];for(var key in object){var value=object[key];if(base)key=base+'['+key+']';var result;switch(utilities.typeOf(value)){case'object':result=toQueryString(value,key);break;case'array':var qs={};value.each(function(val,i){qs[i]=val;});result=toQueryString(qs,key);break;default:result=key+'='+encodeURIComponent(value);break;}
if(value!==null){queryString.push(result);}}
return queryString.join('&');};var ajax=function(options){ var url=options.url||null;var method=options.method?options.method.toUpperCase():"POST";var success=options.success||function(){};var error=options.error||function(){};var async=options.async===undefined?true:options.async;var data=options.data?toQueryString(options.data):null;if(window.XDomainRequest){return XDomainAjax(options);} 
var xhr;try{ xhr=new XMLHttpRequest();}catch(e){ try{xhr=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{xhr=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){ throw"Your browser does not support AJAX and so cannot excecute this method";}}} 
var onStateChange=function(){if(xhr.readyState==4){if(xhr.status>=200&&xhr.status<300){var resp=xhr.responseText;if(options.json){resp=utilities.JSON.decode(resp);}
success(resp,xhr);}else{error(xhr.responseText,xhr);}}
xhr.onreadystatechage=function(){};};xhr.onreadystatechange=onStateChange; if(data&&method=='GET'){url+=(url.indexOf('?')!=-1?'&':'?')+data;data=null;}
xhr.open(method,url,async);if(options.json){xhr.setRequestHeader('Accept','application/json');}else{xhr.setRequestHeader('Accept','text/javascript, text/html, application/xml, text/xml, */*');}
if(data&&(method=="POST"||method=="PUT")){xhr.setRequestHeader('Content-type','application/x-www-form-urlencoded; charset=utf-8');}
xhr.send(data);return xhr;}; var XDomainAjax=function(options){if(!window.XDomainRequest){return null;}
var url=options.url||null;var method=options.method?options.method.toUpperCase():"POST";var success=options.success||function(){};var error=options.error||function(){};var data=options.data||{}; if(window.location.protocol=="http:"){url=url.replace("https:","http:");}else if(window.location.protocol=="https:"){url=url.replace("http:","https:");}
if(options.async){throw"Asyncronous Cross-domain requests are not supported";} 
if(method!="GET"&&method!="POST"){data["_method"]=method;method="POST";}
data=data?toQueryString(data):null; if(data&&method=='GET'){url+=(url.contains('?')?'&':'?')+data;data=null;}
var xdr=new window.XDomainRequest();xdr.onload=function(){var resp=xdr.responseText;if(options.json){resp=utilities.JSON.decode(resp);}
success(resp,xdr);};xdr.onerror=function(){var resp=xdr.responseText||'error';error(resp,xdr);}; xdr.open(method,url,true);xdr.send(data);return xdr;};return ajax;})();return{closeModal:closeModal,getFile:getFile,saveAs:saveFileAs,MIMETYPES:MIMETYPES,setKey:setAPIKey,getUrlFromData:getUrlFromData,revokeFile:revokeFile,getContents:getContents,_oci:openCommIframe};})();
